### ISSUE TITLE
Failed to install on macos 10.13.5 with node 10.5.0

### ISSUE THREAD

**Issue by rodcul** [resin-io/node-ext2fs#30]
`npm i ext2fs@1.0.6` works
`npm i ext2fs@1.0.7` fails

Got the error when trying to update resin-cli
`npm install resin-cli -g`

No prebuilt binaries:

```
prebuild-install WARN install No prebuilt binaries found (target=10.5.0 runtime=node arch=x64 platform=darwin)
```

```
...
6 warnings generated.
  CC(target) Release/obj.target/ext2fs/deps/e2fsprogs/lib/ext2fs/unlink.o
  CC(target) Release/obj.target/ext2fs/deps/e2fsprogs/lib/ext2fs/valid_blk.o
  CC(target) Release/obj.target/ext2fs/deps/e2fsprogs/lib/ext2fs/version.o
  CC(target) Release/obj.target/ext2fs/deps/e2fsprogs/lib/ext2fs/write_bb_file.o
  LIBTOOL-STATIC Release/libext2fs.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/libext2fs.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rodcul/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/Users/rodcul/.nvm/versions/node/v10.5.0/bin/node" "/Users/rodcul/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rodcul/.nvm/versions/node/v10.5.0/lib/node_modules/ext2fs
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ext2fs@1.0.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ext2fs@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rodcul/.npm/_logs/2018-06-26T10_44_36_957Z-debug.log
```

**Comment by rodcul** [comment]
Works using node v9.11.2

```npm i ext2fs@1.0.7 -g

> ext2fs@1.0.7 install /Users/rodcul/.nvm/versions/node/v9.11.2/lib/node_modules/ext2fs
> prebuild-install || node-gyp rebuild

+ ext2fs@1.0.7
added 93 packages in 8.273s
```

**Comment by pimterry** [comment]
Indeed, good debugging both! This is now fixed, so installs should work fine with node 10 everywhere. Thanks for your help :+1:.

**Comment by lurch** [comment]
I wonder if there's any kind of ProcBot that could catch issues like this in future...? :grin:
