### ISSUE TITLE
Could not find build in build/Release with prebuild on AppVeyor

### ISSUE THREAD

**Issue by jhermsmeier** [resin-io/node-ext2fs#34]
```
C:\projects\node-ext2fs\build\Release\bindings.node : warning LNK4088: image being generated due to /FORCE option; image may not run [C:\projects\node-ext2fs\build\bindings.vcxproj]
  bindings.vcxproj -> C:\projects\node-ext2fs\build\Release\\bindings.node
  bindings.vcxproj -> C:\projects\node-ext2fs\build\Release\bindings.pdb (Full PDB)
prebuild ERR! build Error: Could not find build in build/Release
prebuild ERR! build     at Object.exports.noBuild (C:\projects\node-ext2fs\node_modules\prebuild\error.js:2:10)
prebuild ERR! build     at C:\projects\node-ext2fs\node_modules\prebuild\collect-artifacts.js:19:23
prebuild ERR! build     at FSReqWrap.oncomplete (fs.js:135:15)
```

**Comment by jhermsmeier** [comment]
Fixed in https://github.com/resin-io/node-ext2fs/pull/40
